<a href="https://colab.research.google.com/github/gloriabee/DEMovies/blob/main/gold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:

import os
import duckdb

DRIVE_DB= "/content/drive/MyDrive/data_engineering/movies.duckdb"

In [12]:
print("Exists:",os.path.exists(DRIVE_DB))


if os.path.exists(DRIVE_DB):
  print("Drive DB size:",os.path.getsize(DRIVE_DB))

Exists: True
Drive DB size: 1060864

In [13]:
con=duckdb.connect(DRIVE_DB)
con.execute("SHOW TABLES").fetchdf()

                      name
0            movies_bronze
1  movies_directors_silver
2     movies_genres_silver
3            movies_silver
4    movies_writers_silver

In [14]:
movies_df=con.execute("""
SELECT *
FROM movies_silver
""").fetchdf()

In [15]:
movies_df.head()

,tconst,primaryTitle,startYear,rank,averageRating,numVotes,runtimeMinutes
0,tt0111161,The Shawshank Redemption,1994,1,9.3,3246333,142
1,tt0068646,The Godfather,1972,2,9.2,2261044,175
2,tt0468569,The Dark Knight,2008,3,9.1,3233997,152
3,tt0167260,The Lord of the Rings: The Return of the King,2003,4,9.0,2197501,201
4,tt0108052,Schindler's List,1993,5,9.0,1606270,196

In [16]:
movies_writers_df=con.execute("""
SELECT *
FROM movies_writers_silver
""").fetchdf()
movies_writers_df.head()

      tconst                writer
0  tt0111161          Stephen King
1  tt0111161        Frank Darabont
2  tt0068646            Mario Puzo
3  tt0068646  Francis Ford Coppola
4  tt0468569        Jonathan Nolan

In [17]:
movies_directors_df=con.execute("""
SELECT *
FROM movies_directors_silver
""").fetchdf()
movies_directors_df.head()

      tconst              director
0  tt0111161        Frank Darabont
1  tt0068646  Francis Ford Coppola
2  tt0468569     Christopher Nolan
3  tt0167260         Peter Jackson
4  tt0108052      Steven Spielberg

In [19]:
movies_genres_df=con.execute("""
SELECT *
FROM movies_genres_silver
""").fetchdf()
movies_genres_df.head()

      tconst     genre
0  tt0111161     Drama
1  tt0068646     Crime
2  tt0068646     Drama
3  tt0468569     Crime
4  tt0468569  Thriller

### Gold Layer