<a href="https://colab.research.google.com/github/gloriabee/DEMovies/blob/main/silver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import os
import shutil
import duckdb

In [7]:
DRIVE_DB= "/content/drive/MyDrive/data_engineering/movies.duckdb"
LOCAL_DB="/content/movies.duckdb"

In [8]:
print("Exists:",os.path.exists(DRIVE_DB))

Exists: True

In [9]:
if os.path.exists(DRIVE_DB):
  print("Drive DB size:",os.path.getsize(DRIVE_DB))

Drive DB size: 1060864

In [10]:
con=duckdb.connect(DRIVE_DB)

In [11]:
con.execute("SHOW TABLES").fetchdf()

            name
0  movies_bronze

In [12]:
movies_bronze=con.execute("""
SELECT *
FROM movies_bronze
""").fetchdf()

In [13]:
movies_bronze.head()

,tconst,primaryTitle,startYear,rank,averageRating,numVotes,runtimeMinutes,directors,writers,genres,IMDbLink,Title_IMDb_Link
0,tt0111161,The Shawshank Redemption,1994,1,9.3,3246333,142,Frank Darabont,"Stephen King, Frank Darabont",Drama,"""<a href=""""https://www.imdb.com/title/tt011116...","""<a href=""""https://www.imdb.com/title/tt011116..."
1,tt0068646,The Godfather,1972,2,9.2,2261044,175,Francis Ford Coppola,"Mario Puzo, Francis Ford Coppola","Crime, Drama","""<a href=""""https://www.imdb.com/title/tt006864...","""<a href=""""https://www.imdb.com/title/tt006864..."
2,tt0468569,The Dark Knight,2008,3,9.1,3233997,152,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Go...","Crime, Thriller","""<a href=""""https://www.imdb.com/title/tt046856...","""<a href=""""https://www.imdb.com/title/tt046856..."
3,tt0167260,The Lord of the Rings: The Return of the King,2003,4,9.0,2197501,201,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens, P...","Adventure, Drama, Fantasy","""<a href=""""https://www.imdb.com/title/tt016726...","""<a href=""""https://www.imdb.com/title/tt016726..."
4,tt0108052,Schindler's List,1993,5,9.0,1606270,196,Steven Spielberg,"Thomas Keneally, Steven Zaillian","Biography, Drama, History","""<a href=""""https://www.imdb.com/title/tt010805...","""<a href=""""https://www.imdb.com/title/tt010805..."

### Start Silver Transformations