<a href="https://colab.research.google.com/github/gloriabee/DataTest/blob/main/Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from pyspark.sql import SparkSession

In [ ]:
spark= SparkSession.builder.getOrCreate()

In [ ]:
df = spark.createDataFrame([(1,), (2,), (3,)], ["number"])
df.show()

In [ ]:
spark.stop()

In [6]:
import pandas as pd

In [11]:
import requests

In [19]:
url="https://dummyjson.com/products"
fakedata_url="https://fakestoreapi.com/products"

In [21]:
response= requests.get(fakedata_url)
# products=response.json()
# products_data=products['products']
response.json()

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [16]:
products_data[:2]

[{'id': 1,
  'title': 'Essence Mascara Lash Princess',
  'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
  'category': 'beauty',
  'price': 9.99,
  'discountPercentage': 10.48,
  'rating': 2.56,
  'stock': 99,
  'tags': ['beauty', 'mascara'],
  'brand': 'Essence',
  'sku': 'BEA-ESS-ESS-001',
  'weight': 4,
  'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships in 3-5 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 3,
    'comment': 'Would not recommend!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Very satisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Lucas Gordon',
    'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 48,
  'meta': {'createdAt': '2025-10-09T14:47:01.588Z',
   'updatedAt': '2026-05-23T11:27:41.868Z',
   'barcode': '5784719087687',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
 {'id': 2,
  'title': 'Eyeshadow Palette with Mirror',
  'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
  'category': 'beauty',
  'price': 19.99,
  'discountPercentage': 18.19,
  'rating': 2.86,
  'stock': 34,
  'tags': ['beauty', 'eyeshadow'],
  'brand': 'Glamour Beauty',
  'sku': 'BEA-GLA-EYE-002',
  'weight': 9,
  'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
  'warrantyInformation': '1 year warranty',
  'shippingInformation': 'Ships in 2 weeks',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Savannah Gomez',
    'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Awesome product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Christian Perez',
    'reviewerEmail': 'christian.perez@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nicholas Bailey',
    'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 20,
  'meta': {'createdAt': '2024-12-03T11:29:45.706Z',
   'updatedAt': '2025-08-24T16:52:47.806Z',
   'barcode': '9170275171413',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'}]

In [17]:
df_bronze = spark.createDataFrame(products_data)

df_bronze.printSchema()
df_bronze.show(1, truncate=False)

PySparkTypeError: [CANNOT_MERGE_TYPE] Can not merge type `DoubleType` and `LongType`.

In [18]:
df= pd.DataFrame(products_data)
df.head(5)

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-10-09T14:47:01.588Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2024-12-03T11:29:45.706Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-01-08T18:30:12.844Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-11-22T23:28:00.911Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-10-03T07:39:53.470Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [22]:
import kagglehub
path = kagglehub.dataset_download("tiagoadrianunes/imdb-top-5000-movies")

Downloading to /root/.cache/kagglehub/datasets/tiagoadrianunes/imdb-top-5000-movies/486.archive...

100%|██████████| 362k/362k [00:00<00:00, 68.6MB/s]

Extracting files...

In [27]:
import os

In [29]:
print(os.listdir(path))

['results_with_crew.csv']

In [30]:
df = pd.read_csv(os.path.join(path, "results_with_crew.csv"))

df.head(5)

,tconst,primaryTitle,startYear,rank,averageRating,numVotes,runtimeMinutes,directors,writers,genres,IMDbLink,Title_IMDb_Link
0,tt0111161,The Shawshank Redemption,1994,1,9.3,3246333,142,Frank Darabont,"Stephen King, Frank Darabont",Drama,"<a href=""https://www.imdb.com/title/tt0111161""...","<a href=""https://www.imdb.com/title/tt0111161""..."
1,tt0068646,The Godfather,1972,2,9.2,2261044,175,Francis Ford Coppola,"Mario Puzo, Francis Ford Coppola","Crime, Drama","<a href=""https://www.imdb.com/title/tt0068646""...","<a href=""https://www.imdb.com/title/tt0068646""..."
2,tt0468569,The Dark Knight,2008,3,9.1,3233997,152,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Go...","Crime, Thriller","<a href=""https://www.imdb.com/title/tt0468569""...","<a href=""https://www.imdb.com/title/tt0468569""..."
3,tt0167260,The Lord of the Rings: The Return of the King,2003,4,9.0,2197501,201,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens, P...","Adventure, Drama, Fantasy","<a href=""https://www.imdb.com/title/tt0167260""...","<a href=""https://www.imdb.com/title/tt0167260""..."
4,tt0108052,Schindler's List,1993,5,9.0,1606270,196,Steven Spielberg,"Thomas Keneally, Steven Zaillian","Biography, Drama, History","<a href=""https://www.imdb.com/title/tt0108052""...","<a href=""https://www.imdb.com/title/tt0108052""..."

In [31]:
import duckdb

In [32]:
con = duckdb.connect("my_database.duckdb")

In [34]:
pdf= df.toPandas()

AttributeError: 'DataFrame' object has no attribute 'toPandas'

In [35]:
con.register(f"products_tmp", df)
con.execute(f"CREATE OR REPLACE TABLE Products AS SELECT * FROM products_tmp")
con.unregister(f"products_tmp")

In [36]:
con.close()

In [43]:
import duckdb

con = duckdb.connect("my_database.duckdb")

report = """
SELECT tconst, primaryTitle, startYear
FROM Products
WHERE startYear=2026
"""

print(con.execute(report).fetchdf())

con.close()

        tconst                          primaryTitle  startYear
0   tt28089784                            Punjab '95       2026
1   tt33764258                           The Odyssey       2026
2   tt12042730                     Project Hail Mary       2026
3   tt39139925               Dhurandhar: The Revenge       2026
4   tt22084616             Spider-Man: Brand New Day       2026
5   tt35538033                         Resident Evil       2026
6   tt33100314           Remarkably Bright Creatures       2026
7   tt18259538       Avatar Aang: The Last Airbender       2026
8   tt32565993                  The Sheep Detectives       2026
9   tt14173636                            The Invite       2026
10  tt11378946                               Michael       2026
11  tt29355505                           Toy Story 5       2026
12  tt10375624               Voicemails for Isabelle       2026
13  tt32547691                              Pressure       2026
14   tt1756855                       Coyote vs. Acme       2026
15  tt32141377       28 Years Later: The Bone Temple       2026
16  tt26443616                               Hoppers       2026
17  tt29552248                               Swapped       2026
18  tt33071426                             The Drama       2026
19  tt28014327                                Mayday       2026
20  tt30825738  Star Wars: The Mandalorian and Grogu       2026
21  tt32430579                             Crime 101       2026
22  tt27548557                             Dhamaal 4       2026
23  tt27613895                                  GOAT       2026
24  tt26657236                             Backrooms       2026
25   tt8036976                             Send Help       2026
26  tt32642706                               The Rip       2026
27  tt35672862                                 Hokum       2026
28  tt22740896            People We Meet on Vacation       2026
29   tt4357198                 How to Make a Killing       2026
30  tt35064672                            Cocktail 2       2026
31  tt15574124      Peaky Blinders: The Immortal Man       2026
32  tt33978029           Ready or Not 2: Here I Come       2026
33  tt33046197                     The Wrecking Crew       2026
34  tt34685692                   Over Your Dead Body       2026
35  tt32890033                    Minions & Monsters       2026
36  tt27552099            Mike & Nick & Nick & Alice       2026
37  tt31728330                    They Will Kill You       2026
38  tt27681354                           In the Grey       2026
39  tt31170389                        Evil Dead Burn       2026